/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.69
 * Generated at: 2017-06-24 10:53:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\t<title>to-do-App</title>\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("\t\n");
      out.write("\t<meta charset=\"utf-8\">\n");
      out.write("  \t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("\t\n");
      out.write("\t<link href=\"bower_components/bootstrap/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("\t<link href=\"bower_components/angular-ui-bootstrap/dist/ui-bootstrap-csp.css\" rel=\"stylesheet\">\n");
      out.write("\t<link href=\"bower_components/angular-bootstrap-datetimepicker/src/css/datetimepicker.css\" rel=\"stylesheet\">\n");
      out.write("\t<link href=\"bower_components/ng-img-crop/compile/minified/ng-img-crop.css\" rel=\"stylesheet\">\n");
      out.write("\t\n");
      out.write("\t<link href=\"bower_components/angular-toastr/dist/angular-toastr.min.css\" rel=\"stylesheet\">\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t<link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\" rel=\"stylesheet\">\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t<script src=\"bower_components/jquery/dist/jquery.min.js\" type=\"text/javascript\"></script>\n");
      out.write("\t<script src=\"bower_components/bootstrap/dist/js/bootstrap.min.js\" type=\"text/javascript\"></script>\n");
      out.write("\t<script src=\"bower_components/moment/moment.js\"></script>\n");
      out.write("\t<script src=\"bower_components/angular/angular.min.js\" type=\"text/javascript\"></script>\n");
      out.write("\t<script src=\"bower_components/angular-ui-router/release/angular-ui-router.min.js\" type=\"text/javascript\"></script>\n");
      out.write("\t<script src=\"bower_components/angular-ui-bootstrap/dist/ui-bootstrap-tpls.js\" type=\"text/javascript\"></script>\n");
      out.write("\t<script src=\"bower_components/angular-sanitize/angular-sanitize.min.js\" type=\"text/javascript\"></script>\n");
      out.write("\t<script src=\"bower_components/angular-animate/angular-animate.min.js\" type=\"text/javascript\"></script>\n");
      out.write("\t\n");
      out.write("\t<script src=\"bower_components/angular-bootstrap-datetimepicker/src/js/datetimepicker.js\" type=\"text/javascript\"></script>\n");
      out.write("\t<script src=\"bower_components/angular-bootstrap-datetimepicker/src/js/datetimepicker.templates.js\"></script>\n");
      out.write("\t\n");
      out.write("\t<!-- sorting -->\n");
      out.write("\t<script src=\"bower_components/jquery-ui/jquery-ui.js\" type=\"text/javascript\"></script>\n");
      out.write("\t<script src=\"bower_components/ui-sortable/dist/ui-sortable.min.js\" type=\"text/javascript\"></script>\n");
      out.write("\t\n");
      out.write("\t<!-- toastr -->\n");
      out.write("\t<script src=\"bower_components/angular-toastr/dist/angular-toastr.tpls.min.js\" type=\"text/javascript\"></script>\n");
      out.write("\t\n");
      out.write("\t<!-- share with facebook link -->\n");
      out.write("\t<script src=\"https://connect.facebook.net/enUS/all.js\"></script>\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t<script src=\"bower_components/ng-img-crop/compile/minified/ng-img-crop.js\" type=\"text/javascript\"></script>\n");
      out.write("\t\n");
      out.write("\t<script src=\"bower_components/ui-sortable/dist/ui-sortable.js\" type=\"text/javascript\"></script>\n");
      out.write("\n");
      out.write("\t\n");
      out.write("\t<script src=\"js/app.js\" type=\"text/javascript\"></script>\n");
      out.write("\n");
      out.write("\t\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("\t\t<body id=\"Body\">\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t\t<div data-ng-app=\"toDoApp\">\n");
      out.write("\t\t\t\t<div class=\"container-fluid\">\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\t<ui-view></ui-view>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t</body>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<script src=\"js/controller/signUpController.js\" type=\"text/javascript\"></script>\n");
      out.write("\t<script src=\"js/controller/signInController.js\" type=\"text/javascript\"></script>\n");
      out.write("\t<script src=\"js/controller/toDoHomeController.js\" type=\"text/javascript\"></script>\n");
      out.write("\t<script src=\"js/controller/archiveController.js\" type=\"text/javascript\"></script>\n");
      out.write("\t<script src=\"js/controller/remaindersController.js\" type=\"text/javascript\"></script>\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t<script src=\"js/service/toDoHomeService.js\" type=\"text/javascript\"></script>\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t<script src=\"js/validation/signUpValidation.js\" type=\"text/javascript\"></script>\n");
      out.write("\t<script src=\"js/validation/signInValidation.js\" type=\"text/javascript\"></script>\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/signUp.css\">\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/signIn.css\">\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/home.css\">\n");
      out.write("\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
